version: "3"
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app_network
    ports:
      - "8080:8080"
    working_dir: /frontend

  backend:
    build:
      context: ./server
    container_name: backend
    networks:
      - app_network
    ports:
      - "5000:5000"
    working_dir: /server

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

networks:
  app_network:
    driver: bridge
