version: '3'
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080" #CORREÇÃO: O correto é 8080:8080, o front expõe na porta 8080
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/game_db
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d #CORREÇÃO: Aqui foi corrigido para montar toda a pasta
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local

